### ISSUE TITLE
Please release static builds

### ISSUE THREAD

**Issue by rwbc** [codemaniac/pixie#59]
All your binaries need the gcc lib dlls provided...

**Comment by codemaniac** [comment]
Would the solution be to include `-static` linker flag when targeting Windows platform? Or is something else needed?

Can you also provide details on the system config you are testing on?

**Comment by codemaniac** [comment]
> All your binaries need the gcc lib dlls provided...

Would the solution be to include `-static` linker flag when targeting Windows platform? Or is something else needed?

Can you also provide details on the system config you are testing on?

**Comment by rwbc** [comment]
`-static` will fix it
It is also me BTW who has compiled the much faster Pixie from the other issue...

Guenther (RWBC)

**Comment by rwbc** [comment]
System: WIN11 Pro Ryzen 5700G 32 GB Ram (not important though for this issue)

your release (with missing gcc libs included in the programs folder)
```
uci
id name pixie 0.8.2
id author the pixie developers (see AUTHORS file)
option name Hash type spin default 16 min 1 max 256
option name Threads type spin default 1 min 1 max 8
uciok
isready
readyok
position startpos
go depth 15
info score cp 60 depth 1 nodes 20 time 0 nps 20000 pv b1c3
info score cp 10 depth 2 nodes 93 time 0 nps 93000 pv b1c3 b8c6
info score cp 60 depth 3 nodes 631 time 0 nps 631000 pv b1c3 b8c6 g1f3
info score cp 10 depth 4 nodes 1656 time 1 nps 828000 pv b1c3 b8c6 g1f3 g8f6
info score cp 50 depth 5 nodes 3993 time 1 nps 1996500 pv b1c3 b8c6 g1f3 g8f6 d2d4
info score cp 10 depth 6 nodes 13387 time 3 nps 3346750 pv b1c3 b8c6 g1f3 g8f6 d2d4 d7d5
info score cp 30 depth 7 nodes 31498 time 6 nps 4499714 pv b1c3 b8c6 g1f3 g8f6 d2d4 d7d5 e2e3
info score cp 10 depth 8 nodes 99003 time 21 nps 4500136 pv b1c3 b8c6 g1f3 g8f6 d2d4 d7d5 e2e3 e7e6
info score cp 30 depth 9 nodes 203459 time 34 nps 5813114 pv b1c3 b8c6 g1f3 g8f6 d2d4 d7d5 c1f4 e7e6 e2e3
info score cp 25 depth 10 nodes 1198470 time 330 nps 3620755 pv e2e4 g8f6 b1c3 b8c6 g1f3 e7e5 d2d4 f8b4 d4d5 b4c3
info score cp 25 depth 11 nodes 2606956 time 452 nps 5754869 pv e2e4 g8f6 b1c3 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 f8b4 d4c6
info score cp 20 depth 12 nodes 6600934 time 1292 nps 5105130 pv e2e4 g8f6 b1c3 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 f8b4
info score cp 15 depth 13 nodes 18333733 time 3864 nps 4743527 pv e2e4 g8f6 b1c3 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 f8b4 d1d3
info score cp 20 depth 14 nodes 39602778 time 7031 nps 5631794 pv e2e4 g8f6 b1c3 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 f8b4
info score cp 10 depth 15 nodes 172906436 time 43969 nps 3932372 pv e2e4 e7e5 g1f3 f8c5 b1c3 b8c6 f1c4 d7d6 d2d3 g8f6 c1g5
bestmove e2e4
```

my clang compilation (from 3 hours ago)
```
uci
id name pixie 0.8.2 GS
id author the pixie developers (see AUTHORS file)
option name Hash type spin default 16 min 1 max 256
option name Threads type spin default 1 min 1 max 8
uciok
isready
readyok
position startpos
go depth 15
info score cp 60 depth 1 nodes 20 time 0 nps 20000 pv b1c3
info score cp 10 depth 2 nodes 93 time 0 nps 93000 pv b1c3 b8c6
info score cp 60 depth 3 nodes 631 time 0 nps 631000 pv b1c3 b8c6 g1f3
info score cp 10 depth 4 nodes 1656 time 1 nps 828000 pv b1c3 b8c6 g1f3 g8f6
info score cp 50 depth 5 nodes 3993 time 1 nps 1996500 pv b1c3 b8c6 g1f3 g8f6 d2d4
info score cp 10 depth 6 nodes 13387 time 2 nps 4462333 pv b1c3 b8c6 g1f3 g8f6 d2d4 d7d5
info score cp 30 depth 7 nodes 31498 time 6 nps 4499714 pv b1c3 b8c6 g1f3 g8f6 d2d4 d7d5 e2e3
info score cp 10 depth 8 nodes 99003 time 18 nps 5210684 pv b1c3 b8c6 g1f3 g8f6 d2d4 d7d5 e2e3 e7e6
info score cp 30 depth 9 nodes 203459 time 28 nps 7015827 pv b1c3 b8c6 g1f3 g8f6 d2d4 d7d5 c1f4 e7e6 e2e3
info score cp 25 depth 10 nodes 1198470 time 267 nps 4471902 pv e2e4 g8f6 b1c3 b8c6 g1f3 e7e5 d2d4 f8b4 d4d5 b4c3
info score cp 25 depth 11 nodes 2606956 time 382 nps 6806673 pv e2e4 g8f6 b1c3 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 f8b4 d4c6
info score cp 20 depth 12 nodes 6600934 time 1064 nps 6198060 pv e2e4 g8f6 b1c3 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 f8b4
info score cp 15 depth 13 nodes 18333733 time 3194 nps 5738257 pv e2e4 g8f6 b1c3 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 f8b4 d1d3
info score cp 20 depth 14 nodes 39602778 time 5726 nps 6915100 pv e2e4 g8f6 b1c3 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 f8b4
info score cp 10 depth 15 nodes 172906436 time 36751 nps 4704680 pv e2e4 e7e5 g1f3 f8c5 b1c3 b8c6 f1c4 d7d6 d2d3 g8f6 c1g5
bestmove e2e4
```

**Comment by codemaniac** [comment]
> `-static` will fix it It is also me BTW who has compiled the much faster Pixie from the other issue...
> 
> Guenther (RWBC)

Got it! The much faster build was built using `-march=native` flag or was anything beyond this was done?

Also, I added the `-static` flag and is now merged with `main` branch. Should be fixed with the next release

**Comment by rwbc** [comment]
> Got it! The much faster build was built using `-march=native` flag or was anything beyond this was done?
> 
> Also, I added the `-stati`

Yep, I used march= native here, (avx2/bmi2 flags would not make much difference though) but the reason for the speed win was clang, because I also compiled a version to compare with gcc and march=native and it was around the speed of your release version.

BTW I used your openbench makefile. (not familiar with lua and your premake configs).
No idea what exactly does `optimize speed` in this lua script?

```
    filter { "platforms:windows64", "configurations:Release" }
        buildoptions { "-Wall", "-Wextra" }
        linkoptions { "-static" }
        flags { "FatalWarnings", "LinkTimeOptimization" }
        defines { "NDEBUG" }
        optimize "Speed"
```

**Comment by codemaniac** [comment]
It's totally fine to use the `Makefile` in `Openbench` folder - this is only meant for OB but no harm.

I use https://premake.github.io/ to generate the `Makefile` in the project root folder, which is meant for general use (for releases and stuff). `premake5` uses a file called `premake5.lua` to autogenerate the `Makefile` based on the different configurations mentioned in `premake5.lua`. It's just a simpler version of `cmake`. 

`optimize "Speed"` essentially translates into `-03` optimization flag. You can try running `make config=release_windows64 verbose=1` in the project root to see what's happening.
